### ISSUE TITLE
documentation node js-npm

### ISSUE THREAD

**Issue by meach-kaddour** [meach-kaddour/C2N3-Reenforcement#1]
- [x] l'instalation de node js.

- [x] la compilation du sass a partir node-sass

- [x] documentation sur BEM

**Comment by meach-kaddour** [comment]
`documentation sur compilation du sass avec node js`
`documentation sur le BEM pour la nomination du classes sur css`

**Comment by youssefbm** [comment]
ajouter une définition de finie (checklistes)
